### ISSUE TITLE
No create method in readme?

### ISSUE THREAD

**Issue by ACPK** [PipelineDeals/pipelinedeals_api#10]
I am surprised there isn't a create action listed in the Readme.

**Comment by gammons** [comment]
@ACPK Yes, the pipelinedeals_api gem could certainly use a bit of love.  

The create action should behave exactly like a normal rails create, so something like below would work just fine.

```ruby
deal = PipelineDeals::Deal.new
deal.name = "blah"
deal.save
```

**Comment by ACPK** [comment]
I'll add some love and a PR when I get a change!
