### ISSUE TITLE
Is this still valid and maintained?

### ISSUE THREAD

**Issue by chadwilken** [PipelineDeals/pipelinedeals_api#14]
My company is getting ready to integrate with PipelineDeals and I want to make sure this gem is still maintained and is working properly before I use it.

**Comment by dylanegan** [comment]
@chadwilken sorry for the delayed response. Currently this library isn't actively maintained internally, but for the most part it should still be valid to use with the API. I'd be happy to discuss further about your requirements for your integration to figure out where we can be of assistance.
